name: Feature Request
description: Suggest an idea for Kathará
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "Ubuntu 23.04"
    validations:
      required: true
  - type: input
    id: kathara
    attributes:
      label: Kathará Version
      description: "Please provide the Kathará version you are using."
      placeholder: "3.6.3"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: "What happened?"
    validations:
      required: true
  - type: textarea
    id: lab
    attributes:
      label: Network Scenario
      description: "Attach here a network scenario to reproduce the error."
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Which steps do we need to take to reproduce this error?"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: check
    attributes:
      label: Check Command Output
      description: "Add the output of `kathara check`. This will be automatically formatted into code, so no need for backticks."
      render: shell

