name: Feature Request
description: Suggest an idea for Kathará
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: textarea
    id: bug-description
    attributes:
      label: bug
      description: "Is your feature request related to a problem? Please describe."
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: "Why is it a good idea add this feature to Kathará?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "Describe the solution you would like."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: "Describe alternative solutions you have considered."
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
